name: untitled
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  responsive_sizer: ^3.3.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  provider: ^6.1.4
  cloud_firestore: ^5.6.6
  fluttertoast: ^8.2.12
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/launcher_icon.png
